SRC  = $(wildcard *.hs)
EXEC = $(SRC:.hs=)

all: $(EXEC)

%: %.hs
	ghc --make -O2 -threaded -rtsopts $*
	rm $*.o $*.hi
	rm -f $*.dyn_o $*.dyn_hi

clean:
	rm -rf $(wildcard *.o)
	rm -rf $(wildcard *.hi)
	rm -rf $(EXEC)

