include ../Makefile.include

demo:
	./play
	./play1
	./play1 '../../data/videos/rot4.avi -benchmark'
	./grid
	./play3 '../../data/videos/rot4.avi -fps 30' --live
	./play3 '../../data/videos/rot4.avi -fps 30' --chan
	./play3
	./arrows
	./choice
	./loop
	./nocircuit ../../data/videos/rcube.avi
	./circuit ../../data/videos/rcube.avi
	./smon
	./play4
	./play5
	./interface
	./param
	./stand1
	./stand2
	./stand3
	./nogui '../../data/videos/rot4.avi -benchmark'
	./batch '../../data/videos/rot4.avi -benchmark'
	./single ../../data/images/transi/dscn2070.jpg \
		     ../../data/images/transi/dscn2070.jpg

	./play6
	./play0

