#! /bin/bash

echo "Compiling the C wrappers..."
gcc -O2 -Wall `gsl-config --cflags` -c GSL/gslaux.c -o GSL/gslaux.o

echo "Compiling the C wrappers with debugging information..."
gcc  -DDBG -Wall `gsl-config --cflags` -c GSL/gslaux.c -o GSL/debuggslaux.o

echo "Preparing the documentation..."
rm -f doc/*
haddock GSL.hs \
        GSL/Base.hs GSL/Utils.hs \
        GSL/Core.hs --hide=GSL.Core \
        GSL/Wrappers.hs --hide=GSL.Wrappers \
        GSL/Derived.hs --hide=GSL.Derived \
        GSL/Interface.hs --hide=GSL.Interface \
        GSL/Drawing.hs --hide=GSL.Drawing \
        GSL/Instances.hs --hide=GSL.Instances \
        -o doc -h -p GSL/prologue -t GSLHaskell 2> /dev/null

echo "OK"
