ALL = play play2 canny play3 \
      combi0 combi1 combi2 combi3 \
      offline0 offline points \
      playll \
      combi4 \
      state state2 \
      param1 param3 param2 \
      simple offline3 \
      parallel pipeline conc0 conc1 conc-par \
      pose \
      roisel roibrowse roiclass

EASYVISION = ../..

include ../Makefile.include
