ALL = play play0 play1 play2 play3 \
      combi0 combi1 combi2 combi3 combi4 \
      state state2 \
      param1 param2 param3 \
      simple pose \
      roisel roibrowse roiclass
EASYVISION = ../..

include ../Makefile.include
