ALL = demo hessian warp frontal automatch brush \
      detect interpolate hotpoints \
      contours justsave ocr autopano virpano  \
      pseudocolor segments

EASYVISION = ..

include Makefile.include
