#! /bin/bash

echo "Preparing the documentation..."
rm -f doc/*
haddock Vision.hs \
        Vision/Stat.hs \
        Vision/Classifier.hs \
        Vision/Geometry.hs \
        Vision/Autofrontal.hs \
        ImagProc.hs \
        ImagProc/Ipp.hs \
	ImagProc/Ipp/Core.hs \
        ImagProc/Images.hs \
        ImagProc/Ipp/Wrappers.hs \
        ImagProc/ImageProcessing.hs \
        ImagProc/Saddle.hs \
        EasyVision.hs \
        EasyVision/GUI.hs \
        EasyVision/Combinators.hs \
        EasyVision/Parameters.hs \
        ImagProc/Camera.hs \
        EasyVision/Draw.hs \
        EasyVision/Trackball.hs --hide=Ipp.Trackball \
        --use-package=base --use-package=OpenGL \
        -o doc -h -t Vision # 2> /dev/null
