#! /bin/bash

echo "Preparing the documentation..."
rm -f doc/*
haddock Classifier.hs \
        Classifier/Stat.hs \
        Classifier/Base.hs \
        Classifier/Simple.hs \
        Classifier/Kernel.hs \
        Classifier/Neural.hs \
        Classifier/Adaboost.hs \
        Classifier/SVM.hs \
        Classifier/ToyProblems.hs \
        Vision.hs \
        Vision/Geometry.hs \
        Vision/Estimation.hs \
        Vision/Camera.hs \
        Vision/Stereo.hs \
        Vision/Autofrontal.hs \
        ImagProc.hs \
        ImagProc/Ipp.hs \
        ImagProc/Ipp/Wrappers.hs \
        ImagProc/Ipp/Core.hs \
        ImagProc/Images.hs \
        ImagProc/Camera.hs \
        ImagProc/ImageProcessing.hs \
        ImagProc/Pure.hs \
        ImagProc/Saddle.hs \
        ImagProc/Segments.hs \
        ImagProc/Polyline.hs \
        EasyVision.hs \
        EasyVision/GUI.hs \
        EasyVision/Combinators.hs \
        EasyVision/Parameters.hs \
        EasyVision/Draw.hs \
        EasyVision/Trackball.hs --hide=Ipp.Trackball \
        --use-package=base --use-package=OpenGL \
        -o doc -h -t Vision # 2> /dev/null
