#! /bin/bash

echo "Preparing the documentation..."
rm -rf doc/*
mkdir doc/src

SRCS=`ls *.hs``echo ' '``find Util Vision Classifier EasyVision ImagProc \
      | grep .hs | grep -v .hsc | grep -v parser.hs | grep -v adapter.hs`

for file in $SRCS
do HsColour -html -anchor $file > doc/src/`echo $file | sed 's/\//-/g' | sed s/.hs/.html/g`
done

haddock $SRCS \
        -o doc -h -t easyVision -p prologue.txt  -B ~/apps/ghc/lib/ghc-6.10.1/ \
        --source-module="../doc/src/%{MODULE/./-}.html" \
        --source-entity="../doc/src/%{MODULE/./-}.html#%{NAME}"
