/* generated automatically by adapter.hs */

int ippiAdd_8u_C1RSfsx(unsigned char*, int, unsigned char*, int, unsigned char*, int, void*, int);
int ippiSub_8u_C1RSfsx(unsigned char*, int, unsigned char*, int, unsigned char*, int, void*, int);
int ippiAddC_8u_C1RSfsx(unsigned char*, int, unsigned char, unsigned char*, int, void*, int);
int ippiSubC_8u_C1RSfsx(unsigned char*, int, unsigned char, unsigned char*, int, void*, int);
int ippiAddC_32f_C1Rx(float*, int, float, float*, int, void*);
int ippiMulC_32f_C1Rx(float*, int, float, float*, int, void*);
int ippiAdd_32f_C1Rx(float*, int, float*, int, float*, int, void*);
int ippiSub_32f_C1Rx(float*, int, float*, int, float*, int, void*);
int ippiMul_32f_C1Rx(float*, int, float*, int, float*, int, void*);
int ippiDiv_32f_C1Rx(float*, int, float*, int, float*, int, void*);
int ippiAbs_32f_C1Rx(float*, int, float*, int, void*);
int ippiSqrt_32f_C1Rx(float*, int, float*, int, void*);
int ippiMagnitudePack_32f_C1Rx(float*, int, float*, int, void*);
int ippiFFTInitAlloc_R_32fx(void**, int, int, int, int);
int ippiFFTFree_R_32fx(void*);
int ippiFFTGetBufSize_R_32fx(void*, int*);
int ippiFFTFwd_RToPack_32f_C1Rx(float*, int, float*, int, void*, unsigned char*);
int ippiMirror_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, int);
int ippiRemap_8u_C1Rx(unsigned char*, void*, int, void*, float*, int, float*, int, unsigned char*, int, void*, int);
int ippiRemap_8u_C3Rx(unsigned char*, void*, int, void*, float*, int, float*, int, unsigned char*, int, void*, int);
int ippiRemap_32f_C1Rx(float*, void*, int, void*, float*, int, float*, int, float*, int, void*, int);
int ippiSum_8u_C1Rx(unsigned char*, int, void*, double*);
int ippiSum_32f_C1Rx(float*, int, void*, double*, int);
int ippiHistogramRange_8u_C1Rx(unsigned char*, int, void*, int*, int*, int);
int ippiFilterMedian_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, void*, void*);
int ippiFilterMax_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, void*, void*);
int ippiFilterMax_32f_C1Rx(float*, int, float*, int, void*, void*, void*);
int ippiFilterMin_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, void*, void*);
int ippiFilterMin_32f_C1Rx(float*, int, float*, int, void*, void*, void*);
int ippiFilterBox_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, void*, void*);
int ippiFilterBox_32f_C1Rx(float*, int, float*, int, void*, void*, void*);
int ippiFilterSobelVert_32f_C1Rx(float*, int, float*, int, void*);
int ippiFilterSobelHoriz_32f_C1Rx(float*, int, float*, int, void*);
int ippiFilterLaplace_32f_C1Rx(float*, int, float*, int, void*, int);
int ippiFilterGauss_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, int);
int ippiFilterGauss_32f_C1Rx(float*, int, float*, int, void*, int);
int ippiFilterHipass_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, int);
int ippiFilter_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, int*, void*, void*, int);
int ippiFilter_32f_C1Rx(float*, int, float*, int, void*, float*, void*, void*);
int ippiFilterColumn_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, int*, int, int, int);
int ippiFilterColumn_32f_C1Rx(float*, int, float*, int, void*, float*, int, int);
int ippiFilterRow_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, int*, int, int, int);
int ippiFilterRow_32f_C1Rx(float*, int, float*, int, void*, float*, int, int);
int ippiThreshold_Val_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, unsigned char, unsigned char, int);
int ippiThreshold_Val_32f_C1Rx(float*, int, float*, int, void*, float, float, int);
int ippiComputeThreshold_Otsu_8u_C1Rx(unsigned char*, int, void*, unsigned char*);
int ippiCopy_8u_C3C1Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiCopy_8u_C1C3Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiCopy_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiCopy_8u_C3Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiCopy_8u_C1MRx(unsigned char*, int, unsigned char*, int, void*, unsigned char*, int);
int ippiCopy_32f_C1Rx(float*, int, float*, int, void*);
int ippiCopy_32f_C1MRx(float*, int, float*, int, void*, unsigned char*, int);
int ippiSet_8u_C1Rx(unsigned char, unsigned char*, int, void*);
int ippiSet_8u_C3Rx(unsigned char*, unsigned char*, int, void*);
int ippiSet_32f_C1Rx(float, float*, int, void*);
int ippiImageJaehne_32f_C1Rx(float*, int, void*);
int ippiScale_8u32f_C1Rx(unsigned char*, int, float*, int, void*, float, float);
int ippiScale_32f8u_C1Rx(float*, int, unsigned char*, int, void*, float, float);
int ippiMaxIndx_8u_C1Rx(unsigned char*, int, void*, unsigned char*, int*, int*);
int ippiMaxIndx_32f_C1Rx(float*, int, void*, float*, int*, int*);
int ippiMinMax_32f_C1Rx(float*, int, void*, float*, float*);
int ippiMaxEvery_8u_C1IRx(unsigned char*, int, unsigned char*, int, void*);
int ippiMinEvery_8u_C1IRx(unsigned char*, int, unsigned char*, int, void*);
int ippiMaxEvery_32f_C1IRx(float*, int, float*, int, void*);
int ippiMinEvery_32f_C1IRx(float*, int, float*, int, void*);
int ippiAnd_8u_C1Rx(unsigned char*, int, unsigned char*, int, unsigned char*, int, void*);
int ippiOr_8u_C1Rx(unsigned char*, int, unsigned char*, int, unsigned char*, int, void*);
int ippiXor_8u_C1Rx(unsigned char*, int, unsigned char*, int, unsigned char*, int, void*);
int ippiNot_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiCompare_8u_C1Rx(unsigned char*, int, unsigned char*, int, unsigned char*, int, void*, int);
int ippiCompareC_8u_C1Rx(unsigned char*, int, unsigned char, unsigned char*, int, void*, int);
int ippiCompare_32f_C1Rx(float*, int, float*, int, unsigned char*, int, void*, int);
int ippiErode3x3_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiDilate3x3_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiRGBToYUV420_8u_C3P3Rx(unsigned char*, int, void**, int*, void*);
int ippiYUV420ToRGB_8u_P3C3Rx(void**, int*, unsigned char*, int, void*);
int ippiYUV420ToRGB_8u_P3Rx(void**, int*, void**, int, void*);
int ippiRGBToGray_8u_C3C1Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiRGBToHSV_8u_C3Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiHSVToRGB_8u_C3Rx(unsigned char*, int, unsigned char*, int, void*);
int ippiSampleLine_8u_C1Rx(unsigned char*, int, void*, unsigned char*, void*, void*);
int ippiSampleLine_32f_C1Rx(float*, int, void*, float*, void*, void*);
int ippiAbsDiff_8u_C1Rx(unsigned char*, int, unsigned char*, int, unsigned char*, int, void*);
int ippiAbsDiff_32f_C1Rx(float*, int, float*, int, float*, int, void*);
int ippiIntegral_8u32f_C1Rx(unsigned char*, int, float*, int, void*, float);
int ippiSqrIntegral_8u32f64f_C1Rx(unsigned char*, int, float*, int, double*, int, void*, float, double);
int ippiRectStdDev_32f_C1Rx(float*, int, double*, int, float*, int, void*, void*);
int ippiCannyGetSizex(void*, int*);
int ippiCanny_32f8u_C1Rx(float*, int, float*, int, unsigned char*, int, void*, float, float, unsigned char*);
int ippiDistanceTransform_3x3_8u32f_C1Rx(unsigned char*, int, float*, int, void*, float*);
int ippiDistanceTransform_5x5_8u32f_C1Rx(unsigned char*, int, float*, int, void*, float*);
int ippiFastMarchingGetBufferSize_8u32f_C1Rx(void*, int*);
int ippiFastMarching_8u32f_C1Rx(unsigned char*, int, float*, int, void*, float, unsigned char*);
int ippiFloodFillGetSizex(void*, int*);
int ippiFloodFillGetSize_Gradx(void*, int*);
int ippiFloodFill_8Con_8u_C1IRx(unsigned char*, int, void*, void*, unsigned char, void*, unsigned char*);
int ippiFloodFill_Grad8Con_8u_C1IRx(unsigned char*, int, void*, void*, unsigned char, unsigned char, unsigned char, void*, unsigned char*);
int ippiUndistortGetSizex(void*, int*);
int ippiCreateMapCameraUndistort_32f_C1Rx(float*, int, float*, int, void*, float, float, float, float, float, float, float, float, unsigned char*);
int ippiUndistortRadial_8u_C1Rx(unsigned char*, int, unsigned char*, int, void*, float, float, float, float, float, float, unsigned char*);
int ippiUndistortRadial_32f_C1Rx(float*, int, float*, int, void*, float, float, float, float, float, float, unsigned char*);
int ippiUndistortRadial_8u_C3Rx(unsigned char*, int, unsigned char*, int, void*, float, float, float, float, float, float, unsigned char*);
int ippiSegmentWatershedGetBufferSize_8u_C1Rx(void*, int*);
int ippiSegmentWatershed_8u_C1IRx(unsigned char*, int, unsigned char*, int, void*, int, int, unsigned char*);
