#! /bin/bash
mv GSLHaskell.cabal tmpcabal
cp cabal-fixlapack GSLHaskell.cabal
gcc -c -fPIC GSL/lapack-aux.c
gcc -shared -o libauxlapack.so lapack-aux.o
cp libauxlapack.so ~/lib/GSL-0.6/ghc-6.6/
rm lapack-aux.o libauxlapack.so
runhaskell Setup.hs clean
runhaskell Setup.hs configure --prefix=$HOME
runhaskell Setup.hs build
runhaskell Setup.hs install --user
rm GSLHaskell.cabal
mv tmpcabal GSLHaskell.cabal
cd ../apps
runhaskell tests.hs
cd ../src
