#! /bin/bash

function cabalprof {
    echo "Cabal user install..."
    runhaskell Setup.hs configure -p --prefix=$HOME
    runhaskell Setup.hs build
    runhaskell Setup.hs install --user
}

function cabal {
    runhaskell Setup.hs configure --prefix=$HOME
    runhaskell Setup.hs build
    runhaskell Setup.hs install --user
}

function docs {
    rm -f ../doc/*
    haddock GSL.hs \
            GSL/Fourier.hs \
            GSL/Differentiation.hs \
            GSL/Integration.hs \
            GSL/Polynomials.hs \
            GSL/Minimization.hs \
            GSL/Special.hs \
            GSL/Types.hs \
            GSL/Wrappers.hs \
            GSL/Common.hs \
            GSL/LinearAlgebra.hs \
            GSL/LinearAlgebra/Vector.hs \
            GSL/LinearAlgebra/Matrix.hs \
            GSL/LinearAlgebra/Algorithms.hs \
            GSL/Instances.hs \
            GSL/Plot.hs \
            GSL/Lapack.hs \
            -o ../doc -h -p GSL/prologue -t GSLHaskell # 2> /dev/null
}

# -D doc/GSL.haddock \
# --use-package=base \

function tests {
    echo "Performing some tests..."
    (cd ../apps; runhaskell tests)
}


case $1 in

    cleanbuild)
       runhaskell Setup.hs clean
       cabal
       tests
       ;;

    build)
       cabal
       ;;

    tests)
       tests
       ;;

    docs)
       docs
       ;;

    *)
       cabalprof
       docs
       tests
       ;;

esac
