include ../Makefile.include

demo:
	./mirror
	./hessharr
	./warp
	./points
	./imagproc
	./gradient
	./trail
	./pose ../../data/videos/rot4.avi
	./spline
	./transi ../../data/images/transi
	# ./imagproc --photosmp=../../data/images/transi
	./imagproc --photos=../../data/images/transi

